apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    environment: egitim # MySQl podunun eğitim ortamında çalıştığını belirttiğim etiket.
    tier: backend #Uygulamanın arkaplan uygulaması olduğunu belirttiğim etiket.
    app: mysql #Uygulama türünü belirttiğim etiket.
    component: database # Uygulama bileşeninin türünü belirttiğim etiket.
    part-of: wordpress #Veritabanının hangi uygulamanınn parçası olduğunu belirtiğim etiket.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-veribirimi
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-config-veribirimi 
        configMap:
          name: mysql-config
      containers:
        - image: mysql/mysql-server:8.0-aarch64
          name: mysql-pod
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrprss-mysql
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wrprss-mysql
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrprss-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: kubeblog
          volumeMounts:
            - name: mysql-config-veribirimi
              mountPath: /etc/mysql/conf.d/default_auth.cnf
              subPath: default_auth.cnf
            - name: mysql-veribirimi
              mountPath: /var/lib/mysql