apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None # MySQL sunucumuzun cluster dahilinde erişimini istediğimiz için, servisi ClusterIP anahtarı ekledim.