apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-cld
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cloudtech-mydata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-cld-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
