apiVersion: v1
kind: Service
metadata:
  name: mysql-service-cld
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-cld
  clusterIP: None # MySQL sunucumuzun cluster dahilinde erişimini istediğimiz için, servisi ClusterIP anahtarı ekledim.
