apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-cld
  labels:
    environment: egitim # Wordpress podunun eğitim ortamında çalıştığını belirttiğim etiket.
    tier: frontend #Uygulamanın önyüz uygulaması olduğunu belirttiğim etiket.
    app: wordpress-cld #Uygulama türünü belirttiğim etiket.
    component: cms # Uygulama bileşeninin türünü belirttiğim etiket.
    part-of: mysql-cld #Veritabanının hangi uygulamanınn parçası olduğunu belirtiğim etiket.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-cld
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-cld
        tier: frontend
    spec:
      volumes:
      - name: wordpress-veribirimi
        persistentVolumeClaim:
          claimName: wp-pv-cld-claim
      containers:
      - image: wordpress:5.9-apache
        name: wordpress-pod-cld
        ports:
        - containerPort: 80
          name: wordpress-cld
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
                name: wordpress-config-cld
                key: mysql.db.host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
                name: wordpress-config-cld
                key: mysql.db.name
        - name: WORDPRESS_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
                name: wordpress-config-cld
                key: mysql.db.prefix
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wrprss-mysql-cld
              key: mysql-username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wrprss-mysql-cld
              key: mysql-password
        volumeMounts:
        - name: wordpress-veribirimi
          mountPath: /var/www/html
