apiVersion: v1
kind: Service
metadata:
  name: cld-wordpress-servisi
  labels:
    app: wordpress-cld
spec:
  ports:
    - port: 80
      name: wordpress-cld
  selector:
    app: wordpress-cld
    tier: frontend
  type: NodePort
