apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: merhaba-dunya
  namespace: default
spec:
  dnsNames:
    - merhaba.techakademi.com
  secretName: merhaba-dunya-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
