apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demosu
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-demosu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-demosu
    spec:
      containers:
      - image: dalekurt/rancher-demo:latest
        name: rancher-demosu
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-servisi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: rancher-demosu
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "Geçerli bir mail adresi yazmalısın"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-demosu
  namespace: default
spec:
  dnsNames:
    - rancher.techakademi.com
  secretName: rancher-demosu-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-rancher-ingress
spec:
  ingressClassName: nginx
    tls:
    - hosts:
        - rancher.techakademi.com
      secretName: rancher-demosu-tls-staging
  rules:
  - host: rancher.techakademi.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rancher-servisi
            port:
              number: 80
