apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-sertifika-production 
  namespace: default
spec:
  secretName: ssl-sertifika-production
  dnsNames:
  - rancher.techakademi.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer